<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run()
    {
        $books = [
            [
                'title'          => 'Laskar Pelangi',
                'author'         => 'Andrea Hirata',
                'publisher'      => 'Bentang Pustaka',
                'year_published' => 2005,
                'isbn'           => '979-3062-79-7',
                'category'       => 'Novel',
                'synopsis'       => 'Kisah perjuangan sepuluh anak di Belitung dalam menuntut ilmu di tengah keterbatasan.',
                'cover_image'    => null,
                'quantity'       => 5,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Bumi Manusia',
                'author'         => 'Pramoedya Ananta Toer',
                'publisher'      => 'Lentera Dipantara',
                'year_published' => 1980,
                'isbn'           => '979-97312-3-2',
                'category'       => 'Sejarah',
                'synopsis'       => 'Roman sejarah berlatar belakang kebangkitan nasional dan perjuangan Minke.',
                'cover_image'    => null,
                'quantity'       => 3,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Filosofi Teras',
                'author'         => 'Henry Manampiring',
                'publisher'      => 'Kompas',
                'year_published' => 2018,
                'isbn'           => '978-602-412-518-9',
                'category'       => 'Self Improvement',
                'synopsis'       => 'Penerapan filsafat stoisisme kuno untuk mengatasi kekhawatiran dan emosi negatif modern.',
                'cover_image'    => null,
                'quantity'       => 7,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Atomic Habits',
                'author'         => 'James Clear',
                'publisher'      => 'Gramedia Pustaka Utama',
                'year_published' => 2019,
                'isbn'           => '978-602-06-3317-6',
                'category'       => 'Self Improvement',
                'synopsis'       => 'Perubahan kecil yang memberikan hasil luar biasa untuk membangun kebiasaan baik.',
                'cover_image'    => null,
                'quantity'       => 10,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Sapiens: Sejarah Singkat Umat Manusia',
                'author'         => 'Yuval Noah Harari',
                'publisher'      => 'KPG',
                'year_published' => 2011,
                'isbn'           => '978-602-424-647-1',
                'category'       => 'Sains',
                'synopsis'       => 'Penelusuran sejarah perkembangan umat manusia dari zaman batu hingga abad modern.',
                'cover_image'    => null,
                'quantity'       => 4,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Laut Bercerita',
                'author'         => 'Leila S. Chudori',
                'publisher'      => 'Kepustakaan Populer Gramedia',
                'year_published' => 2017,
                'isbn'           => '978-602-424-697-6',
                'category'       => 'Novel',
                'synopsis'       => 'Kisah persahabatan, cinta, dan pengkhianatan sekelompok aktivis mahasiswa di era reformasi.',
                'cover_image'    => null,
                'quantity'       => 6,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Hujan',
                'author'         => 'Tere Liye',
                'publisher'      => 'Gramedia Pustaka Utama',
                'year_published' => 2016,
                'isbn'           => '978-602-03-2478-4',
                'category'       => 'Novel',
                'synopsis'       => 'Kisah persahabatan, cinta, perpisahan, dan perjuangan di dunia masa depan.',
                'cover_image'    => null,
                'quantity'       => 8,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Negeri 5 Menara',
                'author'         => 'Ahmad Fuadi',
                'publisher'      => 'Gramedia Pustaka Utama',
                'year_published' => 2009,
                'isbn'           => '978-979-22-4845-6',
                'category'       => 'Novel',
                'synopsis'       => 'Kisah enam santri dari berbagai daerah Indonesia yang bermimpi menaklukkan dunia.',
                'cover_image'    => null,
                'quantity'       => 4,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Pemrograman Web dengan CodeIgniter 4',
                'author'         => 'Iktiar Dev',
                'publisher'      => 'Informatika',
                'year_published' => 2024,
                'isbn'           => '978-602-875-120-2',
                'category'       => 'Teknologi',
                'synopsis'       => 'Buku panduan lengkap membangun aplikasi web modern menggunakan CodeIgniter 4.',
                'cover_image'    => null,
                'quantity'       => 12,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Ronggeng Dukuh Paruk',
                'author'         => 'Ahmad Tohari',
                'publisher'      => 'Gramedia Pustaka Utama',
                'year_published' => 1982,
                'isbn'           => '979-22-0196-3',
                'category'       => 'Sastra',
                'synopsis'       => 'Trilogi novel tentang kehidupan Srintil, seorang penari ronggeng di sebuah dukuh kecil.',
                'cover_image'    => null,
                'quantity'       => 3,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Sang Pemimpi',
                'author'         => 'Andrea Hirata',
                'publisher'      => 'Bentang Pustaka',
                'year_published' => 2006,
                'isbn'           => '979-3062-92-4',
                'category'       => 'Novel',
                'synopsis'       => 'Kisah persahabatan tiga anak remaja Belitung yang bermimpi untuk bersekolah di Paris.',
                'cover_image'    => null,
                'quantity'       => 5,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
            [
                'title'          => 'Dilan: Dia adalah Dilanku Tahun 1990',
                'author'         => 'Pidi Baiq',
                'publisher'      => 'Pastel Books',
                'year_published' => 2014,
                'isbn'           => '978-602-7870-43-7',
                'category'       => 'Novel',
                'synopsis'       => 'Kisah asmara Dilan dan Milea di SMA Bandung yang penuh warna dan kejutan.',
                'cover_image'    => null,
                'quantity'       => 6,
                'created_at'     => date('Y-m-d H:i:s'),
                'updated_at'     => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('books')->insertBatch($books);
    }
}
